### ISSUE TITLE
只有域名, 没有IP, 如何正确创建client? How to create a client without ip address but domain name?

### ISSUE THREAD

**Issue by RephoneYin** [Gerapy/Gerapy#105]
![image](https://user-images.githubusercontent.com/8410037/56351227-32e60180-61ff-11e9-81f0-724bc183ba9f.png)

很尴尬呀, 只有域名, 没有ip的咋整呀? 
万丈深坑呀!

**Comment by blue-bird1** [comment]
只在前端限制了 修改请求数据就行了

**Comment by blue-bird1** [comment]
docker安装的吧 这个bug早修复了 但是docker镜像没更新

**Comment by RephoneYin** [comment]
@blue-bird1 Thanks a lot

**Comment by Cally99** [comment]
Has the docker image been updated?
