### ISSUE TITLE
项目管理中 创建项目问题

### ISSUE THREAD

**Issue by WuQianyong** [Gerapy/Gerapy#108]
![bug](https://user-images.githubusercontent.com/12892724/58550117-a9830f80-823f-11e9-9c9c-2650b65024b1.png)
使用域名出现了  没有输入框

版本号是 0.8.6 beta2 ， 0.8.5 这一块是正常的

**Comment by Broad-sky** [comment]
我也遇到了这个问题，怎么解决？

**Comment by Broad-sky** [comment]
> ![bug](https://user-images.githubusercontent.com/12892724/58550117-a9830f80-823f-11e9-9c9c-2650b65024b1.png)
> 使用域名出现了 没有输入框
> 
> 版本号是 0.8.6 beta2 ， 0.8.5 这一块是正常的

你的问题解决了吗

**Comment by WuQianyong** [comment]
用回  0.8.5 版本



wuqianyong1995@163.com
 
发件人： Sigma
发送时间： 2019-06-06 16:48
收件人： Gerapy/Gerapy
抄送： WuQianyong; Author
主题： Re: [Gerapy/Gerapy] 项目管理中 创建项目问题 (#108)

使用域名出现了 没有输入框
版本号是 0.8.6 beta2 ， 0.8.5 这一块是正常的
你的问题解决了吗

**Comment by Broad-sky** [comment]
是的，我已经用回0.8.5版本了，谢谢

**Comment by SheaJin1995** [comment]
> 是的，我已经用回0.8.5版本了，谢谢

0.8.5版本好像没看到有定时任务啊，能加个qq交流下吗

**Comment by Broad-sky** [comment]
> > 是的，我已经用回0.8.5版本了，谢谢
> 
> 0.8.5版本好像没看到有定时任务啊，能加个qq交流下吗

QQ：一七四五三七九九六零

**Comment by Germey** [comment]
现在都已经修复，可以尝试最新版本。
