### ISSUE TITLE
gerapy migrate model报错

### ISSUE THREAD

**Issue by low-py** [Gerapy/Gerapy#11]
gerapy init之后，进入gerapy，执行migrate报错

![image](https://user-images.githubusercontent.com/29934976/35087203-49f002fa-fc6a-11e7-83f9-6cc4c22b8b16.png)

**Comment by Germey** [comment]
你的django版本是多少？

**Comment by Germey** [comment]
django 2.0 版本开始，增加了 ForeignKey 的 on_delete 强制传入，如果不加这个就会报错，将 django 降级到 1.x 版本即可，新版本的 requirements 我会修复的，谢谢！

**Comment by Germey** [comment]
现在我直接增加了 Django 2.0 版本的兼容，可以直接更新 Gerapy 新版本，不用降级 Django 了。
