### ISSUE TITLE
想问下，爬虫的运行时日志是如何获取到的

### ISSUE THREAD

**Issue by hiliving** [Gerapy/Gerapy#111]
您好，我在做一个手机客户端，想实时显示运行日志，我看gerapy可以显示运行日志，请教下如何获取的

**Comment by Littlecowherd** [comment]
![image](https://user-images.githubusercontent.com/19882756/64236815-c2c9e500-cf2d-11e9-85f9-076dc74e9741.png)
日志是Scrapyd提供的

**Comment by Littlecowherd** [comment]
https://scrapyd.readthedocs.io/en/stable/
https://piaosanlang.gitbooks.io/spiders/05day/section5.3.html

**Comment by hiliving** [comment]
感谢
