### ISSUE TITLE
Nginx怎么反向代理gerapy？

### ISSUE THREAD

**Issue by downdawn** [Gerapy/Gerapy#120]
ip直接访问太危险了，考虑用Nginx反向代理设置密码，可是location要怎么写？

**Comment by thsheep** [comment]
https://github.com/Gerapy/Gerapy/blob/master/Deploy_Python3/roles/openresty/files/nginx.conf

参考此文件

自己替换 password 文件

password 文件直接制作方法，参考 docs/README.md

**Comment by downdawn** [comment]
`    server {
        listen 6800;
        server_name localhost;

        location / {
                proxy_pass_header Server;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Scheme $scheme;
                proxy_pass http://tornadoes;
                auth_basic 'scrapyd';
                auth_basic_user_file /usr/local/openresty/nginx/conf/scrapyd.passwd;
                }
        }`

nginx主要是这个配置吧，可是6800不是scrapyd的吗？gerapy不是运行在8000端口吗？

**Comment by thsheep** [comment]
替换到你的 Gerapy 就行
