### ISSUE TITLE
gerapy init 初始化时出错

### ISSUE THREAD

**Issue by eflydata** [Gerapy/Gerapy#121]
在win环境下，gerapy init 初始化时出错提示：SyntaxError: Non-UTF-8 code starting with
  修复代码：gerapy-script.py文件首行加上`# -*- coding:utf-8 -*-`
麻烦修复

**Comment by Germey** [comment]
经过我的测试和修复，现在在 Win 10 上未出现此错误，可以试用下最新版本:
```
pip install -U gerapy
```
