### ISSUE TITLE
gerapy进入调度界面，看到正在运行的任务的时间不正确，有时候是正确的，当任务卡住不懂

### ISSUE THREAD

**Issue by HeywoodKing** [Gerapy/Gerapy#123]
![image](https://user-images.githubusercontent.com/22010337/68275554-fb5d7a80-00a6-11ea-8ab2-6e255e4aee46.png)
gerapy进入调度界面，看到正在运行的任务的时间不正确，有时候是正确的，当任务卡住不动了，之后再点击run，然后重新运行一个新进程，但是时间就不对了，而且无法停止部署在centos7系统上的任务，windows上的可以停止，不着调是什么原因

**Comment by thsheep** [comment]
服务器的时间是否和本地时间相同？？

**Comment by HeywoodKing** [comment]
@thsheep 感谢，，，我确认了一下确实是服务器的时间不正确，感谢ing
