### ISSUE TITLE
下午的时间格式化错误。

### ISSUE THREAD

**Issue by tinybright** [Gerapy/Gerapy#131]
**Describe the bug**
下午的时间格式化错误。
下午3点会显示为03。时间选择器打开会选择03 而不是15

**To Reproduce**
1. Go to 'http://localhost:8000/#/task/1/edit'

**Traceback**
Copy traceback displayed in console to here.

**Expected behavior**

**Screenshots**
![{EFB8FFAF-57B4-49DA-BB2A-D76DD7F36DDA}_20200117152024](https://user-images.githubusercontent.com/8720949/72592259-2d0f7f00-393d-11ea-8236-8393e9185155.jpg)

**Environment (please complete the following information):**
 - OS: linux

**Additional context**

**Comment by Germey** [comment]
Fixed in 0.9.8
