### ISSUE TITLE
会自带一个evil 的任务 挖矿[可能是我把scrapyd暴露到公网了,别人可能通过scrapyd给我加了任务]

### ISSUE THREAD

**Issue by tinybright** [Gerapy/Gerapy#133]

**Comment by Germey** [comment]
这个是 gerapy 的问题还是说 scrapyd 等的问题？

**Comment by Germey** [comment]
不用 docker 会这样吗？

**Comment by tinybright** [comment]
不清楚 。我目前可能的原因是我把scrapyd暴露到公网了。别人可能通过scrapyd给我加了项目。

**Comment by tinybright** [comment]
@Germey  要么被扫描了。或者可能是gerapy的问题。进程是  kinsing and kdevtmpfsi.项目是evil

**Comment by Germey** [comment]
我检查一下

**Comment by zzy624** [comment]
我也出现了，是不是有漏洞

**Comment by Germey** [comment]
scrapyd 暴露公网了吗？

**Comment by tinybright** [comment]
@zzy624 可能是scrapyd暴露公网的原因

**Comment by Germey** [comment]
这个应该不属于 Gerapy 的问题了哈，那我先 close 了～
