### ISSUE TITLE
是否可以调度上面考虑 对兼容其他事件

### ISSUE THREAD

**Issue by somewheve** [Gerapy/Gerapy#138]
已经实现了Gerapy 稳定调度爬虫运行 ， 但是我在想能不能不仅仅支持爬虫事件， 
是否可以考虑到兼容一些命令的调度和定时执行。

因为数据控制器很多，不只是爬虫   想在一个界面上做集成控制，不想开多个界面，很麻烦

**Comment by Germey** [comment]
明白了，所以是想说，你想直接输入一些命令，我直接定时执行你定义的命令。

这样的确通用性更好一些，但对于安全性的保障是很低的，比如如果输入一些破坏性的指令，是会干扰到系统的，这种如果在 production 环境是非常危险的。

对此你有什么看法？比如开放部分指令白名单，或者对某些指令加黑名单。

**Comment by somewheve** [comment]
我个人建议让用户自行来做鉴别 自行设置黑名单指令，用户需要知晓自己的行为会带来什么后果。 然后我们提供一份默认的黑名单目录 或者白名单目录 。这样能满足绝大部分的人需求。 我个人意见是这这样

**Comment by Germey** [comment]
谢谢您的建议，我近期会把这个功能开发出来，到时候希望您能帮忙也测试一下，如您能参与优化那更好了，非常感谢！

**Comment by somewheve** [comment]
好的 谢谢大佬  随时关注 我是你粉丝哈哈哈哈    大佬如果有更新了 这里发回复或者发我邮件 somewheve@gmail.com  如果要qq也行  723316072  。 到时候希望能帮的上你

**Comment by Germey** [comment]
好滴！
