### ISSUE TITLE
有点抱歉  但是实在找不到有效的问问题的地方  大佬回复一下我后关闭这个issue  有点冒犯不好意思

### ISSUE THREAD

**Issue by somewheve** [Gerapy/Gerapy#140]
emmmm 问题背景 ：

scrapy

我有生成大量的帖子的url，现在我需要判断当前帖子的datetime时间来 决定是否继续访问下一个url。 但是基于scrapy的yield机制，我无法实现这种校验 。

目前已经尝试解决方案
通过设置一个全局的帖子的时间戳，在进行下一个url请求的时候判断时间是否满足条件。 但是好像还是受限于yield，他不执行，先生成生成器。

搜索引擎都找过 群里面问过 但是好像都没大佬能搞定我的问题

**Comment by thsheep** [comment]
你可以在下载中间件中判断， process_request() 判断一下符合要求的就放行，不符合要求的就放行，不让其进入下载 Downloader。

有个问题在于 如果使用外部数据源的话判断的话会严重降低爬取速度（Redis， MYSQL 等等）。

我的建议是通过启动时候传递参数实现。
