### ISSUE TITLE
获取添加的服务器失败

### ISSUE THREAD

**Issue by Sitoi** [Gerapy/Gerapy#144]
**Describe the bug**

- 添加了服务器，但是页面列表获取不到，状态码显示 401

**Screenshots**

<img width="515" alt="gerapy" src="https://user-images.githubusercontent.com/32479597/76286449-2ff37400-62dd-11ea-96e1-a1cfc0cdee70.png">

**Comment by scil** [comment]
I met same problem and solved it.

just try to run `gerapy initadmin` once or twice.

**Comment by Germey** [comment]
You can also delete the cookies or localstorage and retry login.

If it needs password, you can use `gerapy createsuperuser` to add a user and login.

**Comment by WenKingSu** [comment]
![image](https://user-images.githubusercontent.com/30596340/115683833-6a0cc180-a389-11eb-882e-d2c4004a5596.png)
使用 `gerapy initadmin` 或是 `gerapy createsuperuser` 建立的新User登入，在創建主機時還是會出現`401 Unauthorized`。
請問有解決辦法嗎？
