### ISSUE TITLE
刷新项目列表后，项目的[可配置]和[打包]状态异常

### ISSUE THREAD

**Issue by trennble** [Gerapy/Gerapy#146]
部署方式是使用pip直接部署

异常日志：

> ERROR - 2020-04-20 21:25:08,946 - process: 23993 - build.py - gerapy.server.core.build - 67 - build - error occurred ('settings',)
> INFO - 2020-04-20 21:25:08,947 - process: 23993 - build.py - gerapy.server.core.build - 24 - build - successfully build project JDScrawl to egg file None

界面显示：
![img](https://s1.ax1x.com/2020/04/20/J3SAHS.png)

**Comment by Germey** [comment]
Bug fixed, 0.9.3 released.

Please try the new version of Gerapy:

```
pip3 install -U gerapy
```

or

```
docker run -d -v ~/gerapy:/app/gerapy -p 8000:8000 germey/gerapy:0.9.3
```
Thanks for your support.
