### ISSUE TITLE
docker运行gerapy无法更改密码

### ISSUE THREAD

**Issue by downdawn** [Gerapy/Gerapy#149]
催大，有个问题请教一下。docker运行gerapy，让稍后更改密码，可是前端页面里没有提供更改密码的

docker的run.sh里没有运行gerapy createsuperuser，密码是默认的admin。有没有办法是docker运行时可以配置的，比如环境变量？或者怎么样可以更改密码？谢谢！

**Comment by downdawn** [comment]
已解决，登录Django后台更改密码就行。谢谢了

**Comment by consults** [comment]
http://ip:prot/admin/
进去之后右上角CHANGE PASSWORD修改密码
