### ISSUE TITLE
item和pipelines能否结合一下DjangoItem，使用Django的Model功能

### ISSUE THREAD

**Issue by Siffre** [Gerapy/Gerapy#15]

**Comment by Siffre** [comment]
使用sql语句太过于生硬，大佬求嵌入

**Comment by Germey** [comment]
我目前实现的就是插入操作，传入字典，动态构造了SQL，当然看起来是没有那么友好，用SQLAlchemy, Django 来实现ORM会更好一些，不过这个不是我的刚需，现在用 MongoDB 比较多，我就没多整理。后期会考虑加入这部分内容
