### ISSUE TITLE
KeyError: 'rule'

### ISSUE THREAD

**Issue by lqkweb** [Gerapy/Gerapy#155]
nvs\gerapy\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "d:\soft\miniconda\envs\gerapy\lib\site-packages\scrapy\spiders\crawl.py", line 71, in _response_downloaded
    rule = self._rules[response.meta['rule']]
KeyError: 'rule'

**Comment by Germey** [comment]
Thanks for your issue, I'll check it soon.
