### ISSUE TITLE
Django的admin后台要使用吗？用xadmin替换怎么样？？

### ISSUE THREAD

**Issue by Siffre** [Gerapy/Gerapy#16]

**Comment by Germey** [comment]
django admin 这部分有做，先利用 `gerapy createsuperuser` 创建账户，然后进入 /admin 即可。
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fnna0x46i0j31kw0jnadv.jpg)
这部分其实用的不多，不过可以用来辅助管理。
现在页面没有美化，如果你有兴趣，欢迎一起加入开发。

**Comment by Siffre** [comment]
@Germey 有兴趣，就是水平有点低

**Comment by Germey** [comment]
没事呀，如果有时间可以试着做一下，然后发PR，如果可以的话，我来Merge一下，非常感谢你的支持
