### ISSUE TITLE
 'python3 -m pip install gerapy ' failed on Mac OS 10.15.6

### ISSUE THREAD

**Issue by loveJasmine** [Gerapy/Gerapy#162]
ERROR: Could not find a version that satisfies the requirement incremental>=16.10.1 (from versions: none)
    ERROR: No matching distribution found for incremental>=16.10.1

**Comment by Germey** [comment]
I didn't repro this bug, What's the version of Python?

**Comment by loveJasmine** [comment]
python3.8

**Comment by Germey** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Python 3.8 may not supported well, Please use try 3.6 or 3.7, thanks.
 
    On 08/8/2020 11:26，yk_data<notifications@github.com> wrote： 



python3.8
