### ISSUE TITLE
提示打包失败怎么解决？{"message": "egg not found"}

### ISSUE THREAD

**Issue by xianrenqh** [Gerapy/Gerapy#164]
{"message": "egg not found"}
这是什么原因 
怎么解决

**Comment by Germey** [comment]
Released new test version: https://pypi.org/project/gerapy/0.9.6a1/, please have a try.

**Comment by Germey** [comment]
Version 0.9.6 Released, please try:

```
pip3 install -U gerapy
```

Docker Image also released: https://hub.docker.com/repository/docker/germey/gerapy/general

**Comment by xianrenqh** [comment]
ok, thinks
