### ISSUE TITLE
打包的时候报错 /usr/local/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Scarlett796** [Gerapy/Gerapy#165]
ERROR - process: 15 - build.py - gerapy.server.core.build - 67 - build - error occurred (2, ['/usr/local/bin/python', 'setup.py', 'clean', '-a', 'bdist_egg', '-d', '/tmp/gerapy-mp7_981_'])
打开/tmp/gerapy-mp7_981_文件显示
/usr/local/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory

我找到build.py文件
里面有创建setup的方法，

def create_default_setup_py(path, **kwargs):
    """
    create setup.py file to path
    :param path:
    :param kwargs:
    :return:
    """
    if os.path.exists(path):
        logger.debug('setup.py file already exists at %s', path)
    else:
        with open(join(path, 'setup.py'), 'w', encoding='utf-8') as f:
            file = _SETUP_PY_TEMPLATE % kwargs
            f.write(file)
            f.close()
            logger.debug('successfully created setup.py file at %s', path)
这里的setup.py创建在哪里呢？
有遇到这种情况的吗？怎么解决的？

**Comment by Germey** [comment]
Released new test version: https://pypi.org/project/gerapy/0.9.6a1/, please have a try.

**Comment by Germey** [comment]
Version 0.9.6 Released, please try:

```
pip3 install -U gerapy
```

Docker Image also released: https://hub.docker.com/repository/docker/germey/gerapy/general

**Comment by Scarlett796** [comment]
That has been solved. Thank you
