### ISSUE TITLE
在主机-调度-爬虫的日志界面显示 Processing Failed 是怎么回事啊

### ISSUE THREAD

**Issue by whisperbb** [Gerapy/Gerapy#175]
爬虫是正常运行的，但是应该是scrapy输出的信息位置显示的是这样。。
\<html>\<head>\<title>Processing Failed\</title>\</head>\<body>\<b>Processing Failed\</b>\</body>\</html>

**Comment by DuoCaiXie** [comment]
你好，您解决这个问题了么，我的也是如此

**Comment by whisperbb** [comment]
> 你好，您解决这个问题了么，我的也是如此
没呢，有的项目是正常的，有的就是有问题。。

**Comment by DuoCaiXie** [comment]
我查看了下我的scrapyd日志，发现是零日志，这是为什么呢，你出现这样的情况么

**Comment by whisperbb** [comment]
> 我查看了下我的scrapyd日志，发现是零日志，这是为什么呢，你出现这样的情况么

一样，我也没找到原因，我重新打包然后启动之后gerapy界面的日志正常显示了，但是scrapyd日志里面没有这个项目的日志

**Comment by DuoCaiXie** [comment]
> > 我查看了下我的scrapyd日志，发现是零日志，这是为什么呢，你出现这样的情况么
> 
> 一样，我也没找到原因，我重新打包然后启动之后gerapy界面的日志正常显示了，但是scrapyd日志里面没有这个项目的日志

我手动去命令行里敲代码curl去运行 发现也是没日志的，真是奇怪
