### ISSUE TITLE
docker部署打包失败

### ISSUE THREAD

**Issue by chenxuzhen** [Gerapy/Gerapy#176]
打包错误代码：
[14/Dec/2020 13:42:12] "GET /api/client/1/project/jdspider-master/version HTTP/1.1" 200 78
ERROR - 2020-12-14 13:42:19,441 - process: 15 - build.py - gerapy.server.core.build - 68 - build - error occurred ('settings',)
INFO - 2020-12-14 13:42:19,441 - process: 15 - build.py - gerapy.server.core.build - 24 - build - successfully build project jdspider-master to egg file None
[14/Dec/2020 13:42:19] "POST /api/project/jdspider-master/build HTTP/1.1" 500 28
ERROR - 2020-12-14 13:53:38,197 - process: 15 - build.py - gerapy.server.core.build - 68 - build - error occurred ('settings',)
INFO - 2020-12-14 13:53:38,197 - process: 15 - build.py - gerapy.server.core.build - 24 - build - successfully build project jdspider-master to egg file None
[14/Dec/2020 13:53:38] "POST /api/project/jdspider-master/build HTTP/1.1" 500 28
可以确定是这个函数出了问题，希望得到解决
/app/source/gerapy/server/core/build.py

**Comment by chenxuzhen** [comment]
抱歉，是我没有理解清楚，zip需要压缩整个项目文件夹。晚点再更新

**Comment by Ensuperb** [comment]
同样的问题，希望得到解决。
python的gerapy 
![image](https://user-images.githubusercontent.com/49173457/134759407-0139ca38-bcc9-4777-b706-809f9adb3177.png)

docker 镜像ID 为d90eb5322628，也就是9、25的master镜像。
![image](https://user-images.githubusercontent.com/49173457/134760476-a8f12d81-9f9e-4d3f-8445-bd7e1c9b84ea.png)

**Comment by Germey** [comment]
Closed, please refer to https://github.com/Gerapy/Gerapy/issues/176#issuecomment-744205798
