### ISSUE TITLE
how to specify the database to use?

### ISSUE THREAD

**Issue by mxdev88** [Gerapy/Gerapy#182]
Is it possible to specify the database to use? I did not find how in the documentation. It only mentions SQLite database.
For example, it would be very useful to let gerapy know I want to use another database engine. e.g postgres and give it the connection string so it can create the schema, etc on that database instead.

**Comment by Germey** [comment]
No, it only support SQLite and don't have plan to support other DB, you can modify gerapy/server/server/settings.py to support other DB.
