### ISSUE TITLE
crate project fail

### ISSUE THREAD

**Issue by mrb957600057** [Gerapy/Gerapy#19]
while ctating project ,Failed to Save ,why?

**Comment by thsheep** [comment]
Can be a little more detail？？

**Comment by mrb957600057** [comment]
@thsheep 
when crate a project,browser says  "Failed to Save"
terminal say :+1: TypeError: the JSON object must be str, not 'bytes'
how to do with it?

**Comment by mrb957600057** [comment]
please can you tell me if service redis and mongod before start gerapy?

**Comment by Germey** [comment]
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fnp7u35xoqj30id08hwg2.jpg)
got this traceback offline

**Comment by Germey** [comment]
views.py line 116 change to `request.body.decode('utf-8')`
but this should not happen...

**Comment by Germey** [comment]
@mrb957600057 could you please provide the system info and pip list?

**Comment by microacup** [comment]
@Germey and line 249.

```
data = json.loads(request.body.decode('utf-8'))
```

**Comment by Germey** [comment]
same error on debian:
```
Request Method: | POST
-- | --
http://127.0.0.1:8000/api/client/create
2.0.1
TypeError
the JSON object must be str, not 'bytes'
/usr/lib/python3.5/json/__init__.py in loads, line 312
/usr/bin/python3
3.5.3
['/usr/local/bin',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages']
Mon, 22 Jan 2018 15:23:41 +0800
```

**Comment by mrb957600057** [comment]
@Germey 
Linux 16.0.04
python3.5.2 
pip list:
alabaster (0.7.9)
anaconda-clean (1.0)
anaconda-client (1.5.1)
anaconda-navigator (1.3.1)
APScheduler (3.2.0)
argcomplete (1.0.0)
asn1crypto (0.24.0)
astroid (1.4.7)
astropy (1.2.1)
attrs (17.4.0)
Automat (0.6.0)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0rc1)
beautifulsoup4 (4.5.1)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.2)
boto (2.42.0)
Bottleneck (1.1.0)
bz2file (0.98)
certifi (2018.1.18)
cffi (1.7.0)
chardet (3.0.4)
chest (0.2.3)
click (6.6)
cloudpickle (0.2.1)
clyent (1.2.2)
cognitive-face (1.3.1)
colorama (0.3.7)
conda (4.3.30)
conda-build (2.0.2)
configobj (5.0.6)
constantly (15.1.0)
contextlib2 (0.5.3)
cryptography (2.1.4)
cssselect (1.0.3)
cycler (0.10.0)
Cython (0.24.1)
cytoolz (0.8.0)
dask (0.11.0)
datashape (0.5.2)
decorator (4.0.10)
defusedxml (0.5.0)
dill (0.2.5)
Django (2.0.1)
django-cors-headers (2.1.0)
docopt (0.6.2)
docutils (0.12)
dynd (0.7.3.dev1)
elasticsearch (6.0.0)
et-xmlfile (1.0.1)
fake-useragent (0.1.8)
fastcache (1.0.2)
filelock (2.0.6)
Flask (0.12.1)
Flask-Cors (2.1.2)
Flask-Login (0.4.1)
gensim (3.0.1)
gerapy (0.8.2)
gevent (1.2.2)
greenlet (0.4.12)
h5py (2.6.0)
HeapDict (1.0.0)
html5lib (0.9999999)
hyperlink (17.3.1)
idna (2.1)
imagesize (0.7.1)
incremental (17.5.0)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
jieba (0.39)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.0)
kazoo (2.2.1)
lazy-object-proxy (1.2.1)
llvmlite (0.13.0)
locket (0.2.0)
lru-dict (1.1.6)
lxml (3.7.1)
Markdown (2.6.9)
MarkupSafe (0.23)
matplotlib (1.5.3)
mecab-python (0.0.0)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.8)
nb-anacondacloud (1.2.0)
nb-conda (2.0.0)
nb-conda-kernels (2.0.0)
nbconvert (4.2.0)
nbformat (4.1.0)
nbpresent (3.0.2)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (4.2.3)
numba (0.28.1)
numexpr (2.6.1)
numpy (1.13.3)
odo (0.5.0)
openpyxl (2.3.2)
pandas (0.18.1)
parsel (1.3.1)
partd (0.3.6)
path.py (0.0.0)
pathlib2 (2.1.0)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.0.1)
pickleshare (0.7.4)
pika (0.10.0)
Pillow (3.3.1)
pip (9.0.1)
pkginfo (1.3.2)
ply (3.9)
prompt-toolkit (1.0.3)
protobuf (3.4.0)
psutil (4.3.1)
ptyprocess (0.5.1)
py (1.4.31)
pyasn1 (0.1.9)
pyasn1-modules (0.2.1)
pycnnum (1.0.0)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.43.0)
PyDispatcher (2.0.5)
pyelasticsearch (1.4)
pyflakes (1.3.0)
Pygments (2.1.3)
pylint (1.5.4)
pyltp (0.1.9.1)
pymongo (3.6.0)
PyMySQL (0.8.0)
pyOpenSSL (16.2.0)
pyparsing (2.1.4)
pyquery (1.3.0)
PySocks (1.6.6)
pyspider (0.3.9)
pytest (2.9.2)
python-dateutil (2.5.3)
python-scrapyd-api (2.0.1)
pytz (2016.6.1)
PyYAML (3.12)
pyzmq (15.4.0)
QtAwesome (0.3.3)
qtconsole (4.2.1)
QtPy (1.1.2)
queuelib (1.4.2)
redis (2.10.5)
requests (2.18.4)
rope-py3k (0.9.4.post1)
ruamel-yaml (-VERSION)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.18.1)
Scrapy (1.5.0)
scrapy-redis (0.6.8)
scrapy-splash (0.7.2)
selenium (3.8.0)
service-identity (17.0.0)
setuptools (36.6.0)
simplegeneric (0.8.1)
simplejson (3.13.2)
singledispatch (3.4.0.3)
six (1.11.0)
smart-open (1.5.3)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
SolrClient (0.2.1)
Sphinx (1.4.6)
spyder (3.0.0)
SQLAlchemy (1.0.13)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.3.1)
tblib (1.3.2)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)
terminado (0.6)
toolz (0.8.0)
tornado (4.4.1)
tqdm (4.19.4)
traitlets (4.3.0)
Twisted (17.9.0)
tzlocal (1.5.1)
u-msgpack-python (2.4.1)
unicodecsv (0.14.1)
urllib3 (1.21.1)
w3lib (1.18.0)
wcwidth (0.1.7)
web.py (0.40.dev0)
Werkzeug (0.11.11)
wheel (0.30.0)
widgetsnbextension (1.2.6)
word2vec (0.9.1)
wrapt (1.10.6)
WsgiDAV (2.2.4)
xlrd (1.0.0)
XlsxWriter (0.9.3)
xlwt (1.1.2)
xpinyin (0.5.5)
zope.interface (4.4.3)
alabaster (0.7.9)
anaconda-clean (1.0)
anaconda-client (1.5.1)
anaconda-navigator (1.3.1)
APScheduler (3.2.0)
argcomplete (1.0.0)
asn1crypto (0.24.0)
astroid (1.4.7)
astropy (1.2.1)
attrs (17.4.0)
Automat (0.6.0)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0rc1)
beautifulsoup4 (4.5.1)
bitarray (0.8.1)
blaze (0.10.1)
bleach (1.5.0)
bokeh (0.12.2)
boto (2.42.0)
Bottleneck (1.1.0)
bz2file (0.98)
certifi (2018.1.18)
cffi (1.7.0)
chardet (3.0.4)
chest (0.2.3)
click (6.6)
cloudpickle (0.2.1)
clyent (1.2.2)
cognitive-face (1.3.1)
colorama (0.3.7)
conda (4.3.30)
conda-build (2.0.2)
configobj (5.0.6)
constantly (15.1.0)
contextlib2 (0.5.3)
cryptography (2.1.4)
cssselect (1.0.3)
cycler (0.10.0)
Cython (0.24.1)
cytoolz (0.8.0)
dask (0.11.0)
datashape (0.5.2)
decorator (4.0.10)
defusedxml (0.5.0)
dill (0.2.5)
Django (2.0.1)
django-cors-headers (2.1.0)
docopt (0.6.2)
docutils (0.12)
dynd (0.7.3.dev1)
elasticsearch (6.0.0)
et-xmlfile (1.0.1)
fake-useragent (0.1.8)
fastcache (1.0.2)
filelock (2.0.6)
Flask (0.12.1)
Flask-Cors (2.1.2)
Flask-Login (0.4.1)
gensim (3.0.1)
gerapy (0.8.2)
gevent (1.2.2)
greenlet (0.4.12)
h5py (2.6.0)
HeapDict (1.0.0)
html5lib (0.9999999)
hyperlink (17.3.1)
idna (2.1)
imagesize (0.7.1)
incremental (17.5.0)
ipykernel (4.5.0)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
jieba (0.39)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.0)
kazoo (2.2.1)
lazy-object-proxy (1.2.1)
llvmlite (0.13.0)
locket (0.2.0)
lru-dict (1.1.6)
lxml (3.7.1)
Markdown (2.6.9)
MarkupSafe (0.23)
matplotlib (1.5.3)
mecab-python (0.0.0)
mistune (0.7.3)
mpmath (0.19)
multipledispatch (0.4.8)
nb-anacondacloud (1.2.0)
nb-conda (2.0.0)
nb-conda-kernels (2.0.0)
nbconvert (4.2.0)
nbformat (4.1.0)
nbpresent (3.0.2)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (4.2.3)
numba (0.28.1)
numexpr (2.6.1)
numpy (1.13.3)
odo (0.5.0)
openpyxl (2.3.2)
pandas (0.18.1)
parsel (1.3.1)
partd (0.3.6)
path.py (0.0.0)
pathlib2 (2.1.0)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.0.1)
pickleshare (0.7.4)
pika (0.10.0)
Pillow (3.3.1)
pip (9.0.1)
pkginfo (1.3.2)
ply (3.9)
prompt-toolkit (1.0.3)
protobuf (3.4.0)
psutil (4.3.1)
ptyprocess (0.5.1)
py (1.4.31)
pyasn1 (0.1.9)
pyasn1-modules (0.2.1)
pycnnum (1.0.0)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.43.0)
PyDispatcher (2.0.5)
pyelasticsearch (1.4)
pyflakes (1.3.0)
Pygments (2.1.3)
pylint (1.5.4)
pyltp (0.1.9.1)
pymongo (3.6.0)
PyMySQL (0.8.0)
pyOpenSSL (16.2.0)
pyparsing (2.1.4)
pyquery (1.3.0)
PySocks (1.6.6)
pyspider (0.3.9)
pytest (2.9.2)
python-dateutil (2.5.3)
python-scrapyd-api (2.0.1)
pytz (2016.6.1)
PyYAML (3.12)
pyzmq (15.4.0)
QtAwesome (0.3.3)
qtconsole (4.2.1)
QtPy (1.1.2)
queuelib (1.4.2)
redis (2.10.5)
requests (2.18.4)
rope-py3k (0.9.4.post1)
ruamel-yaml (-VERSION)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.18.1)
Scrapy (1.5.0)
scrapy-redis (0.6.8)
scrapy-splash (0.7.2)
selenium (3.8.0)
service-identity (17.0.0)
setuptools (36.6.0)
simplegeneric (0.8.1)
simplejson (3.13.2)
singledispatch (3.4.0.3)
six (1.11.0)
smart-open (1.5.3)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.3)
SolrClient (0.2.1)
Sphinx (1.4.6)
spyder (3.0.0)
SQLAlchemy (1.0.13)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.3.1)
tblib (1.3.2)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)
terminado (0.6)
toolz (0.8.0)
tornado (4.4.1)
tqdm (4.19.4)
traitlets (4.3.0)
Twisted (17.9.0)
tzlocal (1.5.1)
u-msgpack-python (2.4.1)
unicodecsv (0.14.1)
urllib3 (1.21.1)
w3lib (1.18.0)
wcwidth (0.1.7)
web.py (0.40.dev0)
Werkzeug (0.11.11)
wheel (0.30.0)
widgetsnbextension (1.2.6)
word2vec (0.9.1)
wrapt (1.10.6)
WsgiDAV (2.2.4)
xlrd (1.0.0)
XlsxWriter (0.9.3)
xlwt (1.1.2)
xpinyin (0.5.5)
zope.interface (4.4.3)

**Comment by mrb957600057** [comment]
OK！ thank you! The problem has been resolved  with your solution.
views.py line 116 and line 249  change to request.body.decode('utf-8')
@Germey @Germey @microacup

**Comment by Germey** [comment]
@mrb957600057 thanks~ I'll try to add a middleware to solve these problems of this kind, thanks for your issue.

**Comment by Germey** [comment]
fixed by adding middleware
