### ISSUE TITLE
GitHub Security Lab: Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [Gerapy/Gerapy#197]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to `GHSL-2021-076-gerapy`.

Thank you,  
Agustin Gianni
GitHub Security Lab

**Comment by Germey** [comment]
Thanks, I've updated SECURITY.md and report Security Advisory https://github.com/Gerapy/Gerapy/security/advisories?state=published
