### ISSUE TITLE
把scrapy等封装到一块，做个docker呗。

### ISSUE THREAD

**Issue by nmweizi** [Gerapy/Gerapy#20]

**Comment by thsheep** [comment]
考虑过这样做 问题在于如果打包成Docker 爬虫项目中依赖的额外包 没法处理。

如果使用Dockerfile 又需要使用者有一定的Docker基础。

基于以上原因，Docker就暂时搁置了。

**Comment by BruceDone** [comment]
@thsheep 可以考虑做一个基础镜像，在文档里面进行说明，如果要其它相关的库，需要自己升级镜像的依赖

**Comment by nmweizi** [comment]
@thsheep 做成镜像后，小项目能够直接使用，会方便很多。需要的额外包，都安装上就行了吧。
其实做成Dockerfile，使用也不复杂，就是一两条命令的事，在文档里说明下就行了。

**Comment by Germey** [comment]
@nmweizi @BruceDone 感谢各位，我想尽可能把可能用到的包封装到镜像，保证可以cover大多数爬虫。如果实在有额外的包，就告诉他怎么额外打包吧。
@thsheep 我们搞一个？

**Comment by BruceDone** [comment]
@nmweizi 额外package 需要自己处理的，scrapyd 官方是不是提供Docker 镜像的，另外 @Germey ，首先感谢git主的卓越的贡献，如果考虑docker 镜像的话，尽量通过参数或者环境变量绑定 的host ，不然默认绑定 127.0.0.1,在宿主机上是可以访问的，在其它机器上是访问不了的。

**Comment by thsheep** [comment]
@BruceDone  默认绑定0.0.0.0

**Comment by Germey** [comment]
@thsheep 默认不是 127.0.0.1 吗

**Comment by Germey** [comment]
```
gerapy runserver 0.0.0.0:8000
```
这样才行

**Comment by nmweizi** [comment]
更新好快，感谢。
