### ISSUE TITLE
如api/index/status/、api/client/，末尾“/”结尾的接口都报401

### ISSUE THREAD

**Issue by jiangslee** [Gerapy/Gerapy#207]
# 如```api/index/status/``` ```api/client/```末尾“/”结尾的接口都报401.

**Screenshots**
![image](https://user-images.githubusercontent.com/27892476/131277614-4d71bb97-49a5-4e16-b601-be6905a3841a.png)
![image](https://user-images.githubusercontent.com/27892476/131277631-fc08acec-8362-4f58-bb04-bcb6c8454965.png)

# 我的运行环境
* macOS 11.5
* Python 3.9.6
* Gerapy 0.9.7
* 已运行命令```gerapy init```、```gerapy migrate```、```gerapy createsuperuser```、```gerapy runserver 0.0.0.0:8000```

# 我的解决方案：
### 打开 ```server/core/urls.py ```，将```/$```替换为```$```，重新runserver问题解决
![image](https://user-images.githubusercontent.com/27892476/131277680-b184f702-3d51-4be9-9958-44dc8858c8d7.png)

![image](https://user-images.githubusercontent.com/27892476/131277717-da787a8b-fdea-45c6-a26e-501dec2aca14.png)
![image](https://user-images.githubusercontent.com/27892476/131277795-1fffc6ba-731c-48c5-a8f0-d34b9bd0d975.png)

**Comment by Germey** [comment]
Fixed by https://github.com/Gerapy/Gerapy/pull/208, thanks for your contribution!
