### ISSUE TITLE
Security Issue: GHSL-2021-076-gerapy

### ISSUE THREAD

**Issue by agustingianni** [Gerapy/Gerapy#217]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2021-076-gerapy) in your project on 2021/05/13. It has been 90 days since our initial report and as per our coordinated disclosure policy, we intend to publish a public advisory detailing this issue. If you do wish to further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2021-076-gerapy and we would love to help you resolve these issues. If not, feel free to close this issue after which we will proceed with advisory publication.

**Comment by Germey** [comment]
Fixed in 0.9.9

**Comment by rdotterer09** [comment]
Thank you
