### ISSUE TITLE
请问可以对账户区分权限么？

### ISSUE THREAD

**Issue by KaellLiu** [Gerapy/Gerapy#230]
比如分为管理员和用户权限，管理员可以操作所有，用户只能浏览。

**Comment by Germey** [comment]
目前没有的

**Comment by KaellLiu** [comment]
好的，谢谢

**Comment by KaellLiu** [comment]
![1650273917(1)](https://user-images.githubusercontent.com/13332144/163787977-643937f8-a98d-4cdc-beb4-a7be198a299a.jpg)
还有个问题想请教，这里的距离下次任务为什么会超过100%
