### ISSUE TITLE
一点愚见，崔大

### ISSUE THREAD

**Issue by Amos-x** [Gerapy/Gerapy#26]
首先，作为崔大的学员。希望这个项目能更好。下面是我的一点愚见

看了TodoList。  感觉最紧要需要的功能，不应该是可视化创建爬虫什么的。这是一个分布式部署项目，不是八爪鱼之类的可视化爬虫生成项目。  我个人觉得目前最应该更新的功能如下:

1.  scrapyd 认证，或者是 gerapy 认证。 加scrapyd认证，那么gerapy就放在本地，加gerapy认证，则gerapy放服务器上，都能实现基本的安全认证。不然这个东西根本没办法在生成环境中使用。 就只是一个玩玩的东西

2.  定时任务，生产中最基本的功能，没有这个就不会有人使用gerapy。基本事实就是这样。

希望崔大，先完成这两个基本功能。 别的功能都只是锦上添花，基本的是根基啊。
最后，希望崔大好好干，不断壮大gerapy，写一个广受使用的分布式爬虫部署管理平台。

**Comment by thsheep** [comment]
定时调度正在准备处理。

暂时可以先使用apscheduler来替代

**Comment by Amos-x** [comment]
thsheep，哈哈，是博客上的“哎呀卧槽”呀， 大佬大佬。

话说，认证的不先更新上去吗？ django自带的认证系统也好呀~

**Comment by JiangYinyuan12** [comment]
我给leader 定的2个星期写一个 scrapy 管理界面。刚刚用celery 写好了定时任务。突然看见这个项目，不能再赞了

**Comment by Germey** [comment]
@Amos-x 是的，感谢你的建议，Scrapyd的认证的优先级的确是最高的，我也会尽快把这个加进去，定时任务卧槽哥已经着手在做了，另外感谢卧槽哥 @thsheep 昨天加班加点做完了Docker部署！

**Comment by Germey** [comment]
@JiangYinyuan12 哈哈希望能为你提供帮助~

**Comment by Germey** [comment]
@Amos-x Scrapyd Auth 已经完成并发布：
```
pip3 install gerapy==0.8.4-rc2
```
请试用下看有没有什么问题，如有问题，我及时修复。

**Comment by Germey** [comment]
更新完毕使用之前请先执行：
```
gerapy migrate
```

**Comment by Amos-x** [comment]
晚上试用了一下，问题如下：

1. scrapyd-client的状态更新bug，一直显示绿色正常。任意ip,port都能添加client成功并显示绿色。用错
    误的client进行部署时则提示失败（正确的client还是正常）。 错误的client可以删除，但正确的client无法删除。

2.  验证测试可以通过。但是创建client的时候，提议加一个url路径后缀。方便通过nginx对scrapyd后端client进行统一验证设置，可以通过路径进行区分后端scrapyd实例。 或者有更好的设置验证方式，崔大科普科普~

**Comment by Germey** [comment]
@Amos-x 
1. 我测试了，现在没有出现你说的任意都显示绿色的bug，我任意添加一个，会显示连接错误。
正确的client无法删除确实是外键的问题，现在已经修复了，请更新到最新版本试用。
2. 这个可以详细举个例子吗？不是特别明白你的意思

**Comment by Amos-x** [comment]
第二点的意思是：
scrapyd本身不支持验证，一般通过将其放在nginx后，用nginx做验证并跳转，那么nginx可以通过加一个路径来区分后端的不同的scrapyd服务。
![image](https://user-images.githubusercontent.com/29869322/35364751-d8cea7a6-01ab-11e8-9cef-dde8139f3325.png)

我的提议就是，可以考虑在创建client的时候，要不要增加一个路径的选填框。或者其实最好就直接添加gerapy的用户认证模块，将gerapy放到服务器上，后端的scrapyd都不需要设置验证了（服务器内网不开放出来的），直接用gerapy来管理（只开放gerapy的端口），gerapy就相当于一个统一验证了。

**Comment by Germey** [comment]
感谢你的建议，这个确实在生产环境中是很常见的，我想直接配置的时候加个选项，可以填写Scrapyd Connection URI全路径，如果填写了就以它为高优先级，这样适用范围更广。
后面你说的那个方式的确也是可行的。我之前也考虑过Gerapy远程部署的问题，这样同处于内网的scrapyd就无需加auth了，要远程管理Gerapy，用户认证模块也是需要加的，后期我会考虑加入这个功能的。
另外Gerapy现在已经有了在线编辑功能，所以这也为直接远程使用Gerapy编辑代码提供了支持，这部分功能还需更加健壮一些，比如再加入通过github导入的项目的功能等。
非常感谢~

**Comment by Senmumu** [comment]
最期待功能丰富的调度系统,可视化创建爬虫只是一小部分人的需求.希望能兼容python2.7,就是说,提供不同版本的build选项. 可以实现的方式是选用env build.

**Comment by Germey** [comment]
@Senmumu，感谢你的建议，现在调度系统正在开发中，基本功能已经实现，支持定时间隔调度、指定日期调度、Crontab三种调度方式，使用APScheduler实现。
![](https://ws2.sinaimg.cn/large/006tNc79ly1fo0upfq3eaj30rf0l2tai.jpg)
版本兼容目前据说有小伙伴在2.7直接安装测试没有问题，后面你说的那个build功能的确值得加入，后面也会陆续加入的，感谢你的建议。
