### ISSUE TITLE
为什么添加了服务器按创建之后却没有反应

### ISSUE THREAD

**Issue by XetRAHF** [Gerapy/Gerapy#3]
#创建按钮按下去之后没有反应
<img width="1619" alt="screen shot 2017-10-14 at 5 43 37 am" src="https://user-images.githubusercontent.com/20765594/31567553-b29c4d6c-b035-11e7-9fbc-70f41339b72d.png">
<img width="563" alt="screen shot 2017-10-14 at 5 49 07 am" src="https://user-images.githubusercontent.com/20765594/31567718-7b1ba238-b036-11e7-8a8b-c008b87235fe.png">

**Comment by XetRAHF** [comment]
# 下面这条语句有问题
> data = json.loads(request.body)

您应该使用decode先做一次转换
> data = json.loads(request.body.decode('utf-8'))

大概改了14处，然后解决了这个问题

**Comment by Germey** [comment]
你好，请问你是不是使用的Python2版本，Python3版本是不会出现这个问题的，我先继续开发，后面我会做兼容处理的。
