### ISSUE TITLE
请求支持设置暂停重启。

### ISSUE THREAD

**Issue by mtianyan** [Gerapy/Gerapy#35]
现有对于爬虫状态的管理只有停止和run。希望可以添加自定义爬虫开始命令。添加管理状态暂停。

```
scrapy crawl zhihu -s JOBDIR=job_pause/003
```

**Comment by Germey** [comment]
这个功能其实如果使用了Scrpay-Redis，是可以直接实现的，这个仅限于单机爬虫。我后面会考虑加入一个args来控制，谢谢你的建议
