### ISSUE TITLE
翻译成英文

### ISSUE THREAD

**Issue by Jay54520** [Gerapy/Gerapy#4]
如果我要将所有用户看到的中文翻译成英文，要怎么做？

我现在的想法是使用正则 `[\u4e00-\u9fa5]` 搜索所有 `js` 文件，然后一个一个翻译。

**Comment by Germey** [comment]
其实不用那么做，我前台使用的是Element，它有国际化配置，http://element.eleme.io/#/zh-CN/component/i18n
