### ISSUE TITLE
python2部署爬虫错误

### ISSUE THREAD

**Issue by Origin-Draven** [Gerapy/Gerapy#40]
python2.7， windows7环境下，使用 gerapy 在打包项目 egg 包成功后的 部署 操作时会报错
命令行显示 "POST /api/client/1/project/ICBR/deploy HTTP/1.1" 500 70
检查发现是 gerapy\server\core\views 文件下
第 336 行 scrapyd.add_version(project_name, int(time.time()), egg_file.read()) 引起的
暂时可以选择注释掉这行，便会部署成功，继续调度，爬虫也能正常运行。

**Comment by thsheep** [comment]
没有做Python2兼容  暂时没有做兼容的计划

**Comment by Origin-Draven** [comment]
注释之后会可能导致，页面提示部署成功但不能在页面看到项目，手动在egg包所在目录使用命令scrapyd-deploy ‘服务器名称’ 可暂时解决，再刷新页面，project就有了
