### ISSUE TITLE
English Language Support Feature

### ISSUE THREAD

**Issue by mtaziz** [Gerapy/Gerapy#5]
Hi @Germey , 

Hope you are doing great. I am deeply happy to see you continuously working so hard to improve the performance & adding new feature of Gerapy. 

I know that this is probably not an ideal question to ask you hereon github issue section but I was wondering if you won't mind to let me know when you are expecting to have English support for such an excellent Framework Gerapy.

"In our earlier conversation", you said that "I'm Chinese from Beijing, China. 😁 If you feel any inconvenience I'm glad to convert it in the next version.". 

I am patiently & enthusiastically looking forward to  see support for English. 

Thank you so much for your dedication, time, effort in building such amazing Framework. 

Thank you.

**Comment by Germey** [comment]
@mtaziz Hi, I'm appreciated for your support. In these days I'm preparing for a presentation using Gerapy for my leader, it's more convenient for them to understand using Chinese. Today I'll show them the usage of Gerapy. So after today I'll continue to develop it and add English support, I'm planning to develop a Multilingual Support Version in these days, Thanks!

**Comment by mtaziz** [comment]
@Germey , First off, I would like to wholeheartedly wish you the best luck in your presentation preparation as well  as your upcoming presentation to your leader.  

Really appreciate you taking the time in responding my queries in this regard. 
Thank you very for sharing development plan for Language support. 
I am very happy to hear you. Again, Thank you so much for your effort and time in this regard.

**Comment by Germey** [comment]
@mtaziz Hi, English Support is finished and I'v upgrade Gerapy to 0.7.7, please upgrade it to use.
I've added Chinese/English Support, you can change the language by clicking the button in the top-right corner, and default language is English~

Gerapy is not developed completely, I'll be thankful if you can help me to test Gerapy, if there are something wrong or bug, I'm will be really appreciated if you add a issue. Thanks !

And I've updated the README file, add some instructions:

> You can create a configurable project and then configure and generate code automatically. Also you can drag your Scrapy Project to gerapy/projects folder. Then refresh web, it will appear in the Project Index Page and comes to un-configurable, but you can edit this project in the web interface. As for the deploy, you can move to Deploy Page. Firstly you need to build your project and add client, then you can deploy the project by clicking button. After the deployment, you can manage the job in Monitor Page.

I know the instructions are not completed in detail, I will write a more detailed docs later.

Thanks~

**Comment by mtaziz** [comment]
@Germey , 

Hi, 
I can not thank you enough for being so nice. 
I am very much glad to hear you about English Language support. 
:) SO NICE OF YOU:) !! 

- > In response to Gerapy Accomplishment, I have to admit that Gerapy Development  is very time-and-effort-intensive work, you have done a great job, Hats off to you:)  I believe that you have developed the baseline Framework and eventually different modules will be added over the time. 
I think we can create a section in README that would demonstrate about TO-DO LIST. For example, incomplete task list includes unfinished modules. 

- > Regarding the test, It would be my great pleasure to contribute. I will test thoroughly and share my findings. I will try my best in this regard. 

- >  Thank you very much for the README update. 

- > I believe that I will try to contribute to the documentation, for example, I will add English version's snapshots so that it would be easier for those who don't know the Chinese language. 

Thank you very much for very good work:)
