### ISSUE TITLE
想要從檔案讀取我的scrapyd主機

### ISSUE THREAD

**Issue by hiimdoublej** [Gerapy/Gerapy#52]
你好
想請問如果想要從檔案讀取scrapyd主機的話
具體作法為何？
謝謝

**Comment by thsheep** [comment]
暫時還沒有實現這個功能 

會在後期考慮加入

現在可以試試將Scrapyd主機 寫入SQLite中 core_client表中

**Comment by thsheep** [comment]
歡迎提交代碼 請pr
