### ISSUE TITLE
import gerapy.server.core.scheduler.scheduler

### ISSUE THREAD

**Issue by xiezp** [Gerapy/Gerapy#54]
调度器需要在独立初始化吗？启动之后好像不会自动运行定时作业?大侠们能够提供指导下！

**Comment by thsheep** [comment]
不需要独立初始化  启动Server后 会自动开启新线程运行，

每次调度会有Log提示，

你可以将你的设置的调度方式  贴出来 让我们测试一下

**Comment by xiezp** [comment]
![image](https://user-images.githubusercontent.com/28591704/38778044-2f1b5f00-40e5-11e8-96ae-832ec492d2c0.png)

我就设置了一个间隔10秒执行的爬虫，但是好像不会生效？是不是我设置的不对呢？

另外能否指导下，这个scheduler在哪里初始化的呢？

**Comment by thsheep** [comment]
为了方便开发定时被注释掉了

需要取消注释server/urls 最后两行即可
