### ISSUE TITLE
拉取git最新测试版报错，是因为用了python3.6的f特性吗？

### ISSUE THREAD

**Issue by WangPei0316** [Gerapy/Gerapy#56]
因为我用的3.5.2，报错是
  File "/usr/local/lib/python3.5/dist-packages/gerapy/server/core/scheduler/scheduler.py", line 37
    logger.warning(f"Run {project}: {spider} on server{ip_port.ip}")
                                                                  ^
SyntaxError: invalid syntax
查了一下‘f’是3.6的新功能？？有办法解决吗？

**Comment by Germey** [comment]
@thsheep

**Comment by thsheep** [comment]
OK 没有考虑到兼容性

我更改一下字符串格式方式
