### ISSUE TITLE
client failed to deploy

### ISSUE THREAD

**Issue by shixiaolong55** [Gerapy/Gerapy#66]
抓包发现：状态码500
响应体是：{"message": "AttributeError: 'module' object has no attribute 'time'"}
没有找到解决办法

**Comment by FRANDAVID** [comment]
我也遇到相同问题了,请问是什么原因呢?

**Comment by thsheep** [comment]
麻烦把控制台的错误也贴上来一下

**Comment by woodens** [comment]
[07/Aug/2018 22:48:48] "POST /api/client/2/project/fund_spiders/deploy HTTP/1.1" 500 310

**Comment by Jiang-Fallen** [comment]
浏览器给出的信息是：
Request URL: http://**********/api/client/2/project/PrejectName/deploy
Status Code: 500 Internal Server Error

我尝试打开Request URL所示的地址，得到错误内容如下：
`

Request Method: | GET
-- | --
2.1
ValueError
The view gerapy.server.core.views.project_deploy didn't return an HttpResponse object. It returned None instead.
/usr/local/python3/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response, line 137
/usr/local/python3/bin/python3.7
3.7.0
['/usr/local/python3/bin',  '/usr/local/python3/lib/python37.zip',  '/usr/local/python3/lib/python3.7',  '/usr/local/python3/lib/python3.7/lib-dynload',  '/root/.local/lib/python3.7/site-packages',  '/usr/local/python3/lib/python3.7/site-packages']
Wed, 22 Aug 2018 11:43:13 +0800

`

**Comment by ftutor** [comment]
解决了么？我也遇到了，控制台显示
POST /api/client/1/project/tutorial/deploy HTTP/1.1" 500 70
