### ISSUE TITLE
任务管理中定时任务未能执行？

### ISSUE THREAD

**Issue by lceBoss** [Gerapy/Gerapy#67]
任务管理中定时任务未能执行？所有配置均配置了，定好的时间并不能运行爬虫项目，希望大佬能告知解决办法

**Comment by thsheep** [comment]
你倒是把报错配置什么的贴来上啊

**Comment by lceBoss** [comment]
没有报错，配置时间完成后保存，显示保存成功，但时间到了之后未能执行爬虫项目
![image](https://user-images.githubusercontent.com/16092117/42494600-5412ff46-8453-11e8-9fcb-3ba2f41a9276.png)

**Comment by thsheep** [comment]
定时配错了  

date: 当你想在某个特定时间只运行一次工作时使用(例如：2018年05月14日09:35:10 运行一次)

interval: 当你想以固定的时间间隔运行作业时使用(例如： 每隔十分钟运行一次)

Crontab：当你想在一天中的特定时间周期性地运行工作时使用 (例如： 每天的9点运行一次)

例如 十分钟运行一次 ；就只在 interval 模式下的 分钟输入栏输入10 其余留空

**Comment by AaronJny** [comment]
> 定时配错了
> 
> date: 当你想在某个特定时间只运行一次工作时使用(例如：2018年05月14日09:35:10 运行一次)
> 
> interval: 当你想以固定的时间间隔运行作业时使用(例如： 每隔十分钟运行一次)
> 
> Crontab：当你想在一天中的特定时间周期性地运行工作时使用 (例如： 每天的9点运行一次)
> 
> 例如 十分钟运行一次 ；就只在 interval 模式下的 分钟输入栏输入10 其余留空

按照说明，使用interval配置定时任务，在分钟栏输入1，想要每分钟执行一次，其余留空，进行提交，会提示“不能为空”的错误。请问是怎么回事？麻烦您了，多谢。

![image](https://user-images.githubusercontent.com/20944488/45618150-5e591000-baa7-11e8-93d2-8723e8267f6c.png)

**Comment by thsheep** [comment]
@AaronJny 我记得默认是0 啊  你不是给清空了

**Comment by AaronJny** [comment]
> @AaronJny 我记得默认是0 啊 你不是给清空了

@thsheep 不是我清空的，我今天又确认了一下，的确是空，不是0。
我安装的版本是 gerapy (0.8.6b1)，是在pypi 上看到的最新版本，不知道是不是版本问题。
我尝试将运行时间的其他参数都填了0，运行通过。
感谢卧槽哥。
