### ISSUE TITLE
load error错误

### ISSUE THREAD

**Issue by kevinwu199** [Gerapy/Gerapy#71]
`如果打开了一个查看status页面`http://localhost:8000/#/task/11/status`，然后删除一个定时任务，则会报错
![qq 20180720170642](https://user-images.githubusercontent.com/9098529/42994041-9bf40f78-8c3f-11e8-84a0-c3dc745f4b81.png)

**Comment by Germey** [comment]
fixed, please try the latest version:

```
pip install -U gerapy
```
