### ISSUE TITLE
为什么看不到代码编辑的页面？

### ISSUE THREAD

**Issue by xiaomM** [Gerapy/Gerapy#81]
您好，我今天使用了一下您的工程，没有找到代码编辑的界面是为什么？
我看到README上面是有这个界面的

**Comment by thsheep** [comment]
看不到的话 控制台应该有报错吧 贴出来看一下

**Comment by downdawn** [comment]
![image](https://user-images.githubusercontent.com/41266749/50075361-af4ce180-0219-11e9-87a3-58d48e11e364.png)
这个编辑页面找不到。。

**Comment by Germey** [comment]
Try the latest version:
```
pip install -U gerapy
```
