### ISSUE TITLE
项目问题很多

### ISSUE THREAD

**Issue by hanwangkun** [Gerapy/Gerapy#82]
今天试用了一下，起初看起来不错，但是真正用起来，发现不少问题，从现在来看无法投入使用。
问题如下，还请尽快完善：
1、无法直接在页面上编辑项目文件，也无法看到整个项目的结构；
2、添加spider的页面上各个控件没有相应的示例，导致无法知道要填写成什么样的格式，对于使用者学习和试错的成本 比较大；
3、中英文切换有问题，从中文页面切换到另一页面，自动变成英文；
4、无法删除已经部署的spider

**Comment by Germey** [comment]
是的，项目目前还未到1.0版本，问题的确不少，目前也正在完善中。
1. 这个在线编辑我这边测试是没问题的，项目结构的话应该是可以看到的吧，通过左边的树形。
2. 这方面文档确实不够完善，我后面会继续完善这部分的说明，此部分可视化配置是后来加上的。
3. 对，这个没有做持久化，如果刷新之后会自动切回来。
4. 这部分也没有加，我平时都是直接覆盖掉了，不过这部分需求还是有的，后面也会继续完善。
谢谢您的建议！

**Comment by eflydata** [comment]
今天测试了一下，不是一般的多问题，重安装到现在还无法运行。比如说：
1、中英文切换问题
2、win环境下安装好，第一个错误是ut8编码问题
3、好不容易添加好scrapyd服务端，打包时候win下不支持的，这个说明文档应该说明只支持linux，或提供方法
4、运行这个项目，好像都是帮助修复的bug的路上。。。

**Comment by Germey** [comment]
修复了一些问题，欢迎使用最新版本。
