### ISSUE TITLE
scrapy 爬虫部署到主机时发生setting文件读取错误

### ISSUE THREAD

**Issue by FRANDAVID** [Gerapy/Gerapy#83]
一个写好的scrapy项目,通过图形界面部署到gerapy主机时,部署失败,后台的错误日志如下,
不知道是什么原因.

{ message: 'scrapyd_api.exceptions.ScrapydResponseError: Traceback (most recent call last):\\n  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main\\n    "__main__", fname, loader, pkg_name)\\n  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code\\n    exec code in run_globals\\n  File "/usr/local/lib/python2.7/dist-packages/scrapyd/runner.py", line 40, in <module>\\n    main()\\n  File "/usr/local/lib/python2.7/dist-packages/scrapyd/runner.py", line 37, in main\\n    execute()\\n  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 110, in execute\\n    settings = get_project_settings()\\n  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 68, in get_project_settings\\n    settings.setmodule(settings_module_path, priority=\'project\')\\n  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 292, in setmodule\\n    module = import_module(module)\\n  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module\\n    __import__(name)\\nImportError: No module named CNKISpider.settings\\n' } } }

**Comment by thsheep** [comment]
不支持2哦

**Comment by thsheep** [comment]
本身实现逻辑问题 可以把错误贴出来 修复一下
