### ISSUE TITLE
定时任务调度已经删除，但任务仍在运行。

### ISSUE THREAD

**Issue by AaronJny** [Gerapy/Gerapy#84]
使用的版本为 gerapy (0.8.6b1)。
在卧槽哥@thsheep 的指导下，终于成功让定时任务跑起来了（感激），但紧接着就发现了一个问题。
我添加的定时任务是一个测试脚本，就是简单用来测试定时任务是否可用的。测试完成后，我将添加的定时任务删除，但却发现，在“主机管理”--“选择主机”--“调度”中看到任务运行记录，删掉了定时调度，定时任务却依然按照之前的定时调度执行。。。
另外，卧槽哥能否给个crontab配置的示例，跟linux下面不太一样，不太确定gerapy里面crontab的约定格式是怎样的。多谢！

**Comment by thsheep** [comment]
这个有小问题 你需要重新启动一下。还没处理。

**Comment by AaronJny** [comment]
> 这个有小问题 你需要重新启动一下。还没处理。
谢卧槽哥@thsheep。请问是重启机器还是重启服务？我尝试了重启gerapy和scrapyd，但是都没有效果。

**Comment by qinzimo** [comment]
> 使用的版本为 gerapy (0.8.6b1)。
> 在卧槽哥@thsheep 的指导下，终于成功让定时任务跑起来了（感激），但紧接着就发现了一个问题。
> 我添加的定时任务是一个测试脚本，就是简单用来测试定时任务是否可用的。测试完成后，我将添加的定时任务删除，但却发现，在“主机管理”--“选择主机”--“调度”中看到任务运行记录，删掉了定时调度，定时任务却依然按照之前的定时调度执行。。。
> 另外，卧槽哥能否给个crontab配置的示例，跟linux下面不太一样，不太确定gerapy里面crontab的约定格式是怎样的。多谢！

调度着怎么设置的啊？能给个例子吗 crontab 和interval

**Comment by Germey** [comment]
FIxed, please try the latest version:
```
pip install -U gerapy
```
