### ISSUE TITLE
gerapy通过pip install安装的版本和最新master-0.8.6-beta版本功能是否有差异

### ISSUE THREAD

**Issue by FRANDAVID** [Gerapy/Gerapy#85]
@thsheep 卧槽哥，问个问题，我发现通过pip install gerapy 安装的版本，和github上0.8.6下载的版本有点差异呢，0.8.6的版本嫩开发自定义爬虫时没找到，“生成代码”这个按钮在哪里，但是通过pip 安装的版本就有这个按钮。是我打开的姿势不对么？

**Comment by Germey** [comment]
0.8.6b1 版本把保存和生成按钮合并为一个按钮了，都在右下角，点一下自动保存和生成代码。
