### ISSUE TITLE
Configure UI host and port

### ISSUE THREAD

**Issue by Paw2Pom** [Gerapy/Gerapy#9]
I have installed gerapy on a docker container, however I can only access the UI if the development server starts at http://0.0.0.0:8000 instead of http://127.0.0.1:8000.

Is there any way to configure it like: 

gerapy runserver 0.0.0.0:8000

Many thanks!

**Comment by Germey** [comment]
Sorry, I didn't add this feature in former version.
I've added this feature in Gerapy 0.7.8, please upgrade it, hope it works well for you.

**Comment by Germey** [comment]
Version upgraded to 0.8.0, please upgrade to 0.8.0.
