### ISSUE TITLE
为什么点击停止，爬虫停止不了

### ISSUE THREAD

**Issue by shixianqing** [Gerapy/Gerapy#90]
![image](https://user-images.githubusercontent.com/43101321/49273888-78549d00-f4b1-11e8-96d3-e8874b1c6574.png)

**Comment by hantmac** [comment]
至少要点连续击两次-三次，这是由于scrapyd的关闭机制造成的。

**Comment by HeywoodKing** [comment]
我发现部署在centos7 系统上的都是点击停止好多次都没法停止，部署在windows系统上的点击停止都可以停止，这是什么问题呢？

**Comment by HeywoodKing** [comment]
![image](https://user-images.githubusercontent.com/22010337/68368368-e51cf080-0172-11ea-9844-d702c944fd49.png)
经过多次测试，发现linux(centos7)部署了两台，都会出现运行一段时间之后，卡主不动，然后点击stop之后没有停止，多次点击停止仍是没有停止

**Comment by HeywoodKing** [comment]
> 至少要点连续击两次-三次，这是由于scrapyd的关闭机制造成的。
![image](https://user-images.githubusercontent.com/22010337/68368517-2e6d4000-0173-11ea-97da-f9e443681523.png)

经过多次测试，发现linux(centos7)部署了两台，都会出现运行一段时间之后，卡主不动，然后点击stop之后没有停止，多次点击停止仍是没有停止

**Comment by Germey** [comment]
如果没法停就是 scrapyd 那边的问题了，此界面表示取消请求已经发送成功了。有时候在爬虫十分忙碌或者爬取速度过快的时候需要连续点多次才能停止。如果还是停不了，只能手动去杀死了。
