### ISSUE TITLE
无法输出json文件

### ISSUE THREAD

**Issue by Gladysgong** [Gerapy/Gerapy#94]
本地运行爬虫时，会把爬虫数据存储为json文件，放到gerapy中deploy后运行，日志中显示已抓取到数据，但并未有json文件输出。

**Comment by Gladysgong** [comment]
是我的问题😂我没找对位置。

**Comment by YEUNGWAIPANG** [comment]
> 是我的问题😂我没找对位置。

您好，我想请问一下如果在pipeline中指定了爬取的数据保存在本地的话在哪里可以找得到呢?
