### ISSUE TITLE
ip illegal check: docker-for-mac/docker-for-windows support `host.docker.internal`, but Gerapy say it illegal

### ISSUE THREAD

**Issue by Danceiny** [Gerapy/Gerapy#99]
![snipaste_2019-02-28_17-24-17](https://user-images.githubusercontent.com/9427454/53555895-cc891f00-3b7d-11e9-9d40-f73641051532.png)

**Comment by Danceiny** [comment]
when update the host ip, gerapy say port cannot be empty???
I installed and tried Gerapy by docker.

**Comment by Germey** [comment]
fixed，try the lastest version.
